#
# NOTICE: Influxdb must be started first, initially, to create the tokens for writing and reading data. These
# will be used by the data collector scripts and grafana.
# $ docker-compose --env-file ./.env up -d influxdb
# $ docker-compose --env-file ./.env up -d mosquitto
# $ docker-compose --env-file ./.env up -d
# 
version: "3.7"
services:
  grafana:
    image: docker.io/grafana/grafana-oss:8.2.6
    network_mode: host
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_ANONYMOUS_ORG_NAME=${GF_AUTH_ANONYMOUS_ORG_NAME}
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/plugins:/var/lib/grafana/plugins"
    
  influxdb: 
    image: docker.io/influxdb:2.7.0-alpine
    network_mode: host
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - 'influxdb_data:/var/lib/influxdb2'

  mosquitto:
    image: "eclipse-mosquitto:2.0.17"
    network_mode: host
    restart: always
    volumes:
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"


volumes:
  grafana_data:
    driver: local
  influxdb_data:
    driver: local